### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by shineyruan** [dnaihao/Simulation-Prediction-Market#1]
Have you guys validated that the current market price always matches the current market maker's belief (nu)? I see that the current market maker's belief has been deleted as a parameter in your final code.

**Comment by yihellen** [comment]
Why would these two be equal in the first place?

**Comment by yihellen** [comment]
No

**Comment by yihellen** [comment]
But if we have implemented correctly, that should have been the case.
I think we have implemented correctly though :/

**Comment by shineyruan** [comment]
Alright but it’s better to validate it a little bit though
