### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by shineyruan** [dnaihao/Simulation-Prediction-Market#2]
Could you guys provide how to run the code in command line (what arguments should I pass in, etc)?

**Comment by yihellen** [comment]
I believe you need to pass in some arguments, which include the number of agents and the maximum number of iteration. Check out the argument parser part to figure this out.

**Comment by dnaihao** [comment]
```./simulation_prediction_market.py --agent_number 1 --max_iteration 100```

And you are ready to go.
